(function(){var f=f||{};FIRSTLOAD=!0;SOMETHINGOPEN=!1;f.tools={canRun:function(){var a=navigator.userAgent.toLowerCase();return(a=-1!=a.indexOf("msie")?parseInt(a.split("msie")[1]):!1)?8<a?!0:!1:!0},uniqid:function(){var a=Math.floor(11*Math.random()),d=Math.floor(1E6*Math.random());return String.fromCharCode(a)+d},hideEverything:function(){if(SOMETHINGOPEN){targetThis=SOMETHINGOPEN=!1;for(var a=document.getElementsByTagName("div"),d=0;d<a.length;d++)a[d].hasAttribute("data-cuteselect-options")&&
(a[d].style.opacity="0",a[d].style.display="none")}},getStyle:function(){var a="",d=document.styleSheets,a="";for(s=0;s<d.length;s++)for(var e=d[s].rules||d[s].cssRules,b=0;b<e.length;b++)if(void 0!=e[b].selectorText){var c=e[b].selectorText.indexOf("select"),f=e[b].selectorText.indexOf("option"),h=e[b].selectorText.charAt(c-1),k=e[b].selectorText.charAt(f-1);!(0<=c&&0<=f)||""!=h&&"}"!=h&&" "!=h||""!=k&&"}"!=k&&" "!=k?(0<=c&&(c=e[b].selectorText.charAt(c-1),""==c||"}"==c||" "==c)&&(text=e[b].cssText?
e[b].cssText:e[b].style.cssText,a+=text.replace(/\bselect\b/g,"[data-cuteselect-item]")),0<=f&&(c=e[b].selectorText.charAt(f-1),""==c||"}"==c||" "==c)&&(text=e[b].cssText?e[b].cssText:e[b].style.cssText,a+=text.replace(/\boption\b/g,"[data-cuteselect-value]"))):(text=e[b].cssText?e[b].cssText:e[b].style.cssText,a+=text.replace(/\boption\b/g,"[data-cuteselect-value]").replace(/\bselect\b/g,"[data-cuteselect-item]"))}return a},createSelect:function(a){var d=document.createElement("div");a.hasAttribute("id")&&
(d.setAttribute("id",a.getAttribute("id")),a.removeAttribute("id"));a.hasAttribute("class")&&(d.setAttribute("class",a.getAttribute("class")),a.removeAttribute("class"));a.style.display="none";for(var e=null,b=a.getElementsByTagName("option"),c=0;c<b.length;c++)if(e=b[0].innerHTML,b[c].hasAttribute("selected")){e=b[c].innerHTML;break}for(var g="<div data-cuteselect-title>"+e+"</div><div data-cuteselect-options><div data-cuteselect-options-container>",b=a.getElementsByTagName("option"),c=0;c<b.length;c++)if(!b[c].hasAttribute("disabled"))var h=
b[c].hasAttribute("class")?' class="'+b[c].getAttribute("class")+'"':"",k=b[c].hasAttribute("id")?' id="'+b[c].getAttribute("id")+'"':"",g=b[c].hasAttribute("selected")?g+('<div data-cuteselect-value="'+b[c].value+'" data-cuteselect-selected="true"'+h+k+">"+b[c].innerHTML+"</div>"):g+('<div data-cuteselect-value="'+b[c].value+'"'+h+k+">"+b[c].innerHTML+"</div>");g+="</div></div>";d.innerHTML=e;d.setAttribute("data-cuteselect-item",f.tools.uniqid());d.innerHTML=g;a.setAttribute("data-cuteselect-target",
d.getAttribute("data-cuteselect-item"));a.parentNode.insertBefore(d,a.nextSibling);f.tools.hideEverything()},show:function(a){a.parentNode.hasAttribute("data-cuteselect-item")?a.parentNode.getAttribute("data-cuteselect-item"):a.getAttribute("data-cuteselect-item");var d=document.getElementsByTagName("select");a.hasAttribute("data-cuteselect-title")&&(a=a.parentNode);for(var d=a.getElementsByTagName("div"),e=0;e<d.length;e++)d[e].hasAttribute("data-cuteselect-options")&&(targetItem=d[e],d[e].style.display=
"block",setTimeout(function(){targetItem.style.opacity="1"},10),d[e].style.top=a.offsetTop+a.offsetHeight+"px");a.focus();SOMETHINGOPEN=a.getAttribute("data-cuteselect-item")},selectOption:function(a){var d=a.innerHTML,e=a.getAttribute("data-cuteselect-value"),b=a.parentNode.parentNode.parentNode;a=b.getAttribute("data-cuteselect-item");for(var b=b.getElementsByTagName("div"),c=0;c<b.length;c++)b[c].hasAttribute("data-cuteselect-title")&&
(b[c].innerHTML=d);b=document.getElementsByTagName("select");for(c=0;c<b.length;c++)b[c].getAttribute("data-cuteselect-target")==a&&(b[c].value=e);f.tools.hideEverything()},writeStyles:function(){toWrite='<style type="text/css">'+f.tools.getStyle()+" [data-cuteselect-options] { opacity: 0; display: none; }</style>";document.write(toWrite)}};f.event={parse:function(){for(var a=document.getElementsByTagName("select"),d=0;d<a.length;d++)f.tools.createSelect(a[d])},listen:function(){document.onkeydown=
function(a){a=a||window.event;27==a.keyCode&&f.tools.hideEverything()};document.onclick=function(a){FIRSTLOAD=!1;if(!a.target.getAttribute("data-cuteselect-item")&&!a.target.getAttribute("data-cuteselect-value")&&!a.target.hasAttribute("data-cuteselect-title")||(a.target.hasAttribute("data-cuteselect-item")||a.target.hasAttribute("data-cuteselect-title"))&&SOMETHINGOPEN)f.tools.hideEverything();else{var d=a.target;a.target.getAttribute("data-cuteselect-value")?(f.tools.selectOption(d),f.tools.hideEverything()):
f.tools.show(d);return!1}}},manage:function(){f.tools.canRun()&&(f.event.parse(),f.event.listen(),f.tools.writeStyles())}};f.event.manage()})();
